### ISSUE TITLE
[Bugs] 2.15.1 AppImage Run error

### ISSUE THREAD

**Issue by zxp19821005** [XilinJia/Xilinota#26]
## Environment

Xilinota version:2.15.1
Platform: Linux
OS specifics: EndeavourOS （ArchLinux）

## Steps to reproduce
```
chmod +x Xilinota-2.15.1.AppImage
```
## Describe what you expected to happen
Run error
## Logfile
```
$ ./xilinota-2.15.1.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './ElectronAppWrapper'
Require stack:
- /tmp/.mount_xilinoYGEqBl/resources/app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:114716)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/tmp/.mount_xilinoYGEqBl/resources/app.asar/main.js:5:28)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
```

**Comment by XilinJia** [comment]
Thanks for reporting.

That was successfully built with Github Actions with Ubuntu 20.04.  I just downloaded and tested it and indeed I got the same error on Manjaro.  Very sorry for that, will investigate.

In the mean time, I replaced the 2.15.1 AppImage file in the release with the one built on my Manjaro system and that is the one I use.  I think that should run on your system.  Let me know.

**Comment by zxp19821005** [comment]
It's OK now.I've ported it to AUR:  https://aur.archlinux.org/packages/xilinota-bin in 2023-11-28.

**Comment by XilinJia** [comment]
Thanks very much.  Did you build from source, or use my AppImage?

**Comment by zxp19821005** [comment]
There are two version:
1.Build from source: https://aur.archlinux.org/packages/xilinota-git
2.Use your AppImage: https://aur.archlinux.org/packages/xilinota-bin
I can add you to co-maintainer if you wish.

**Comment by XilinJia** [comment]
> I can add you to co-maintainer if you wish.

I haven't done any AUR scripting, but sure, I'll learn pick it up.

**Comment by grepsuzette** [comment]
By the way, same errors for the mac release (still version 2.15.1, .dmg):

```
Uncaught Exception:
Error: Cannot find module './ElectronAppWrapper'
Require stack:
- /Applications/Xilinota.app/Contents/Resources/app.asar/main.js
- 
at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
at n._resolveFilename (node:electron/js2c/browser_init:2:114716)
at Module._load (node:internal/modules/cjs/loader:929:27)
at l._load (node:electron/js2c/asar_bundle:2:13642)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/Applications/Xilinota.app/Contents/Resources/app.asar/main.js:5:28)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
```
